### ISSUE TITLE
cosinor.lm does not work with tidy dataframes.

### ISSUE THREAD

**Issue by StijnDeVos** [sachsmc/cosinor#5]
I noticed that cosinor does not work with tidy dataframes:

    dat <- readr::read_csv(data_location)
    class(dat) # "tbl_df"     "tbl"        "data.frame"

    mod <- cosinor.lm(y ~ time(time), period = 1440, data = dat)

This gives an error:

    Error in model.frame.default(formula = newformula, data = data, na.action = na.action,  : 
    invalid type (list) for variable 'rrr'

The error occurs in this line:

    data$rrr <- cos(2 * pi * data[, timevar]/period) # from body(cosinor.lm)

Running just this line for my data set gives the error message:

    Error: Unsupported index type: function

I don't know if this should be the responsibility of the user or not... Please ignore this if that is the case!

**Comment by sachsmc** [comment]
I think this is a bug, which looks like an easy fix. I'll keep you posted. Thanks!

**Comment by AndreaMarti1** [comment]
I am receiving an error which I believe could be related to this issue. I sometimes get the following error:

Error in model.frame.default(formula = newformula, data = data, na.action = na.action,  : 
  invalid type (list) for variable 'rrr'

But then sometimes I do not get the error. I do not know what I man doing correct/wrong. Any suggestions? Stuck on this error at the moment.

**Comment by sachsmc** [comment]
@AndreaMarti1 @StijnDeVos can you try installing the sachsmc-patch-1 branch and see if that fixes the problem with tibbles? 

    devtools::install_github("sachsmc/cosinor@sachsmc-patch-1")

**Comment by StijnDeVos** [comment]
After installing from that branch, I wrote the dataset "vitamind" to disk and then read it into R using read_csv:

` x <- readr::read_csv(choose.files())`
`class(x)`
`[1] "tbl_df"     "tbl"        "data.frame"`
`colnames(x)`
`[1] "X"    "Y"    "time"`
`cosinor.lm(Y ~ time(time), period = 1440, data = x)`

An error was returned:

> Error: lazy-load database 'C:/Users/Stijn/Documents/R/win-library/3.5/cosinor/R/cosinor.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1
